name: art_et_jardin
description: "Art & Jardin - App mobile employes terrain"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  table_calendar: ^3.2.0
  fl_chart: ^0.70.2
  flutter_pdfview: ^1.4.0
  signature: ^5.5.0
  url_launcher: ^6.3.1

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.8.1

  # Networking
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.2
  socket_io_client: ^3.0.2

  # Local database
  drift: ^2.25.0
  sqlite3_flutter_libs: ^0.5.30
  path_provider: ^2.1.5

  # Storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  # Auth / Biometric
  local_auth: ^2.3.0

  # Camera / Location
  image_picker: ^1.1.2
  geolocator: ^13.0.2
  mobile_scanner: ^6.0.5

  # Firebase
  firebase_core: ^3.12.1
  firebase_messaging: ^15.2.4
  flutter_local_notifications: ^18.0.1

  # Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0

  # Utils
  intl: ^0.20.2
  vibration: ^2.0.1
  image: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code generation
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  riverpod_generator: ^2.6.5
  drift_dev: ^2.25.0

  # Testing
  mocktail: ^1.0.4
  fake_async: ^1.3.2

flutter:
  uses-material-design: true
